const PRECO={nova:4,captura:2,arriscar:3},VOLTAS=3,MOEDAS=12,TURNO_S=45,TOAST_MS=5200;
const ORDEM=["voce","nara","ivo"],CASOS=window.MC_CASOS||{},REGRAS=window.MC_RULES;
const NOMES={voce:"Você",nara:"Nara",ivo:"Ivo"},FIGURAS=window.MC_ASSETS||{},OVELHA_SRC="ovelha.svg?v=foto-real";
let casoId="ovelha",PECAS={},CAMPOS=[],timerId=null,timerLeft=TURNO_S,toastTimer=null,flipTimer=null;
const state={monte:[],balaio:[],maosPorJogador:{},saldosPorJogador:{},resolvidosGlobais:{},errosPorJogador:{},pagas:{},vez:0,voltasFeitas:{},turnoId:0,turnoTerminaEm:null,verbo:null,log:"",pistasAbertas:true};
const $=s=>document.querySelector(s);
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);}
function show(id){document.querySelectorAll(".scene").forEach(el=>el.classList.toggle("active",el.id===id));}
function shuffle(list){const a=list.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function carregarCaso(id){const c=CASOS[id]||CASOS.ovelha;casoId=c.id;PECAS=c.pecas;CAMPOS=c.campos;const t=$("#caso-titulo");if(t)t.textContent=c.titulo;atualizarRegra();return c;}
function casoAtual(){return CASOS[casoId];}
function modoQuiz(){return REGRAS.modoDoCaso(casoAtual())==="quiz";}
function jogoOnline(){return!!(window.MC_SALA&&window.MC_SALA.online);}
function idJogadorLocal(){return jogoOnline()&&window.MC_SALA.uid?window.MC_SALA.uid:"voce";}
function quem(){return ORDEM[state.vez%ORDEM.length];}
function suaVez(){return quem()===idJogadorLocal();}
function mao(id){return state.maosPorJogador[id]||[];}
function saldo(id){return Number(state.saldosPorJogador[id]||0);}
function mudarSaldo(id,n){state.saldosPorJogador[id]=saldo(id)+n;}
function peca(id){return PECAS[id];}
function say(msg){state.log=msg;render();}
function eOvelha(id){const p=peca(id);return!!(p&&(p.bonus||(casoId==="ovelha"&&(p.figura==="ovelha"||p.protegida))));}
function eProtegida(id){const p=peca(id);return!!(p&&(p.protegida||eOvelha(id)));}
function adicionarOvelhasBonus(){if(modoQuiz()||casoId==="ovelha")return[];const modelo=CASOS.ovelha&&CASOS.ovelha.pecas&&CASOS.ovelha.pecas.F4;if(!modelo)return[];return Array.from({length:REGRAS.quantidadeBonus(ORDEM.length)},function(_,i){const id="BONUS_OVELHA_"+(i+1);PECAS[id]=Object.assign({},modelo,{id:id,bonus:true});return id;});}
function acabou(){return modoQuiz()?CAMPOS.length>0&&CAMPOS.every(c=>state.resolvidosGlobais[c.id]):ORDEM.every(id=>(state.voltasFeitas[id]||0)>=VOLTAS);}
function campoDisponivel(id,jogador){return REGRAS.campoDisponivel(state,jogador,id);}

function paintTimer(){const el=$("#tempo"),cell=$("#cell-tempo");if(!el)return;if(modoQuiz()){el.textContent="livre";cell.classList.remove("minha-vez","vez-alheia","urgente");return;}if(state.turnoTerminaEm)timerLeft=Math.max(0,Math.ceil((state.turnoTerminaEm-Date.now())/1000));el.textContent=Math.floor(timerLeft/60)+":"+String(timerLeft%60).padStart(2,"0");cell.classList.toggle("minha-vez",suaVez());cell.classList.toggle("vez-alheia",!suaVez());cell.classList.toggle("urgente",suaVez()&&timerLeft<=10);}
function stopTimer(){if(timerId)clearInterval(timerId);timerId=null;}
function startTimer(deadline){stopTimer();if(modoQuiz()){state.turnoTerminaEm=null;paintTimer();return;}state.turnoTerminaEm=deadline||Date.now()+TURNO_S*1000;paintTimer();timerId=setInterval(function(){paintTimer();if(timerLeft===0){stopTimer();if(suaVez())say("O tempo terminou. A vez aguarda sua ação ou a condução do Mestre.");}},500);}
function showBagToast(){if(modoQuiz())return;const el=$("#bag-toast");if(!el)return;if(toastTimer)clearTimeout(toastTimer);el.hidden=false;el.classList.remove("out");el.classList.add("in");toastTimer=setTimeout(function(){el.classList.remove("in");el.classList.add("out");setTimeout(function(){el.hidden=true;el.classList.remove("out");},450);},TOAST_MS);}
function dropStamp(x,y){const trail=$("#coin-trail");if(!trail)return;const s=document.createElement("i");s.className="coin-stamp";Object.assign(s.style,{left:x+"px",top:y+"px",width:"24px",height:"24px"});s.style.setProperty("--rot","8deg");trail.appendChild(s);setTimeout(()=>s.classList.add("fade"),900);setTimeout(()=>s.remove(),2050);}
function playCoinIntro(){if(modoQuiz())return;const fly=$("#coin-fly"),dest=document.querySelector(".stash-art .coin"),trail=$("#coin-trail");if(!fly||!dest)return;document.body.classList.add("coin-intro-lock");dest.classList.remove("on");if(trail)trail.innerHTML="";fly.hidden=false;fly.classList.remove("rise","home");const box=dest.getBoundingClientRect();fly.style.setProperty("--tx",box.left+box.width/2+"px");fly.style.setProperty("--ty",box.top+box.height/2+"px");fly.style.setProperty("--end",Math.max(22,box.width)+"px");void fly.offsetWidth;fly.classList.add("rise");setTimeout(function(){fly.classList.remove("rise");void fly.offsetWidth;fly.classList.add("home");let n=0,lastX=null,lastY=null;const spacing=20,started=performance.now();function sample(){const r=fly.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;if(lastX===null){dropStamp(x,y);lastX=x;lastY=y;n++;}let dist=Math.hypot(x-lastX,y-lastY);while(dist>=spacing&&n<32){const ratio=spacing/dist;lastX+=(x-lastX)*ratio;lastY+=(y-lastY)*ratio;dropStamp(lastX,lastY);n++;dist=Math.hypot(x-lastX,y-lastY);}if(performance.now()-started<860&&n<32)requestAnimationFrame(sample);}requestAnimationFrame(sample);},1550);setTimeout(function(){fly.hidden=true;fly.classList.remove("home","rise");dest.classList.add("on");document.body.classList.remove("coin-intro-lock");},2480);}
function revelarCompra(id,jogador,depois){if(!eOvelha(id)){if(depois)depois();return;}const p=peca(id),stage=$("#flip-stage"),front=$("#flip-front"),msg=$("#flip-msg"),inner=$("#flip-inner");if(!stage||!front){if(depois)depois();return;}front.innerHTML="<small>"+esc(p.marca)+"</small><img class='ovelha-art' alt='Ovelha perdida' src='"+OVELHA_SRC+"'><p>"+esc(p.texto)+"</p>";msg.textContent=jogador===idJogadorLocal()?"Você achou a ovelha. A compra não cobra, vale 6 denários e a carta sai do jogo.":(NOMES[jogador]||"Alguém")+" achou a ovelha.";if(inner){inner.style.animation="none";void inner.offsetWidth;inner.style.animation="";}stage.hidden=false;if(flipTimer)clearTimeout(flipTimer);flipTimer=setTimeout(function(){stage.hidden=true;if(depois)depois();},5500);}
function pagarRecompensa(id,jogador){const p=peca(id);if(!p||!p.recompensa||state.pagas[id])return;state.pagas[id]=jogador;mudarSaldo(jogador,p.recompensa);}

function prepararOrdemOnline(){if(!jogoOnline()||!window.MC_SALA.jogadores.length)return;ORDEM.length=0;window.MC_SALA.jogadores.forEach(function(j){ORDEM.push(j.id);NOMES[j.id]=j.nome||"Jogador";});}
function publicarEstado(fase){if(window.MC_GAME&&window.MC_GAME.publicarEstado)window.MC_GAME.publicarEstado(fase||"deal");}
function startDeal(){prepararOrdemOnline();carregarCaso(casoId);PECAS=Object.assign({},casoAtual().pecas);const base=REGRAS.criarEstadoJogadores(ORDEM,modoQuiz()?0:MOEDAS);state.saldosPorJogador=base.saldosPorJogador;state.errosPorJogador=base.errosPorJogador;state.maosPorJogador=base.maosPorJogador;state.voltasFeitas=base.voltasFeitas;state.resolvidosGlobais={};state.balaio=[];state.pagas={};state.vez=0;state.turnoId=1;state.verbo=null;state.pistasAbertas=true;const bonus=adicionarOvelhasBonus(),ids=Object.keys(PECAS),especial=casoId==="ovelha"?ids.find(eOvelha):null,fatos=shuffle(ids.filter(id=>id!==especial&&!bonus.includes(id)));let cursor=0;ORDEM.forEach(function(id){state.maosPorJogador[id]=fatos.slice(cursor,cursor+2);cursor+=2;});const resto=fatos.slice(cursor);state.monte=especial?[especial].concat(resto):shuffle(resto.concat(bonus));state.log=modoQuiz()?"Dois fragmentos para cada participante. Compre um fragmento ou leia um que já possui.":casoId==="ovelha"?"A vez é sua. A primeira compra demonstra a carta da ovelha.":bonus.length+" ovelha(s) bônus foram embaralhadas no monte.";show("deal");window.scrollTo(0,0);startTimer();render();if(!modoQuiz()){showBagToast();requestAnimationFrame(()=>requestAnimationFrame(playCoinIntro));}publicarEstado("deal");}
function passarVez(){state.voltasFeitas[quem()]=(state.voltasFeitas[quem()]||0)+1;state.verbo=null;state.turnoId++;if(acabou()){stopTimer();render();publicarEstado("jogo");setTimeout(fechar,500);return;}state.vez++;if(!modoQuiz())while((state.voltasFeitas[quem()]||0)>=VOLTAS)state.vez++;state.log="Vez de "+(NOMES[quem()]||"jogador")+".";startTimer();render();publicarEstado("deal");if(!suaVez()&&!jogoOnline())setTimeout(jogarRival,650);}

function comprar(indice){if(!suaVez()||!state.monte.length)return say("O poço está vazio.");const jogador=idJogadorLocal(),pos=Math.max(0,Math.min(Number(indice)||0,state.monte.length-1)),id=state.monte[pos],achou=eOvelha(id),custo=modoQuiz()||achou?0:PRECO.nova;if(saldo(jogador)<custo)return say("Saldo insuficiente para comprar.");state.monte.splice(pos,1);mudarSaldo(jogador,-custo);if(!achou)mao(jogador).push(id);revelarCompra(id,jogador,function(){pagarRecompensa(id,jogador);state.log=achou?"A ovelha saiu do jogo. Recompensa: +6.":(modoQuiz()?"Fragmento comprado: ":"Pista comprada: ")+peca(id).marca+".";passarVez();});render();}
function capturar(alvoId,pecaId){const jogador=idJogadorLocal();if(modoQuiz())return lerPista(pecaId);if(eProtegida(pecaId))return say("Essa pista não pode ser capturada.");if(saldo(jogador)<PRECO.captura)return say("Saldo insuficiente para capturar.");const alvo=mao(alvoId);if(!alvo.includes(pecaId))return say("Essa pista já saiu.");state.maosPorJogador[alvoId]=alvo.filter(id=>id!==pecaId);mao(jogador).push(pecaId);mudarSaldo(jogador,-PRECO.captura);pagarRecompensa(pecaId,jogador);state.log="Você capturou "+peca(pecaId).marca+" de "+(NOMES[alvoId]||"outro jogador")+".";passarVez();}
function consignar(pecaId){if(modoQuiz()){if(acabou())fechar();else say("A revelação abre quando os quatro campos estiverem resolvidos.");return;}const jogador=idJogadorLocal();if(!mao(jogador).includes(pecaId))return;state.maosPorJogador[jogador]=mao(jogador).filter(id=>id!==pecaId);state.balaio.push({id:pecaId,dono:jogador});state.log="Você consignou "+peca(pecaId).marca+" no balaio.";passarVez();}
function lerPista(pecaId){const jogador=idJogadorLocal();if(!mao(jogador).includes(pecaId))return;state.log=(NOMES[jogador]||"Jogador")+" leu em voz alta: “"+peca(pecaId).texto+"”";passarVez();}
function arriscar(campoId,valor){const jogador=idJogadorLocal(),campo=CAMPOS.find(c=>c.id===campoId);if(!campo||!campoDisponivel(campoId,jogador))return say("Esse campo já está fechado para você.");const ok=valor===campo.resposta;if(!modoQuiz()&&!ok&&saldo(jogador)<PRECO.arriscar)return say("Saldo insuficiente para bancar o erro.");const resultado=REGRAS.aplicarResposta(state,jogador,campo,valor);if(!resultado.aplicado)return;if(!ok&&!modoQuiz())mudarSaldo(jogador,-PRECO.arriscar);state.log=ok?"Resposta correta. Este campo fechou para todos.":"Resposta incorreta. Este campo fechou somente para você.";passarVez();}
function jogarRival(){if(jogoOnline()||acabou())return;const id=quem();if(id===idJogadorLocal())return;if(state.monte.length){const nova=state.monte.shift();if(!eOvelha(nova))mao(id).push(nova);revelarCompra(nova,id,function(){pagarRecompensa(nova,id);state.log=NOMES[id]+" comprou uma peça.";passarVez();});return render();}if(mao(id).length)state.log=NOMES[id]+" leu uma de suas pistas.";passarVez();}
function abrirVerbo(verbo){if(!suaVez())return;if(modoQuiz()&&verbo==="consignar")return consignar();state.verbo=state.verbo===verbo?null:verbo;render();}

function htmlPainel(){const v=state.verbo,jogador=idJogadorLocal();if(!v||!suaVez())return"";if(v==="comprar")return state.monte.length?"<p>Toque em uma carta do leque para revelar "+(modoQuiz()?"um fragmento.":"uma pista.")+"</p>":"<p>O poço está vazio.</p>";if(v==="capturar"&&modoQuiz())return"<p>Escolha um fragmento seu para lê-lo em voz alta.</p>"+mao(jogador).map(id=>"<button class='chip' type='button' data-act='ler-ok' data-id='"+id+"'><small>Ler fragmento</small>"+esc(peca(id).marca)+"</button>").join("");if(v==="capturar"){const alvos=ORDEM.filter(id=>id!==jogador&&mao(id).length),chips=alvos.map(id=>mao(id).filter(pid=>!eProtegida(pid)).map(pid=>"<button class='chip' type='button' data-act='capturar-ok' data-quem='"+id+"' data-id='"+pid+"'><small>"+esc(NOMES[id])+" · 2</small>"+esc(peca(pid).marca)+"</button>").join("")).join("");return chips?"<p>Escolha uma pista capturável.</p>"+chips:"<p>Não há pista capturável à vista.</p>";}if(v==="consignar")return"<p>Escolha a pista que vai ao balaio.</p>"+mao(jogador).map(id=>"<button class='chip' type='button' data-act='consignar-ok' data-id='"+id+"'><small>Consignar</small>"+esc(peca(id).marca)+"</button>").join("");if(v==="arriscar"){const abertos=CAMPOS.filter(c=>campoDisponivel(c.id,jogador));if(!abertos.length)return"<p>Não há campos disponíveis para você.</p>";return(modoQuiz()?"<p>O acerto fecha o campo para todos; o erro, só para você.</p>":"<p>Se errar, o risco custa 3.</p>")+abertos.map(c=>"<div class='campo-resposta'><b>"+esc(c.rotulo)+"</b>"+c.opcoes.map(o=>"<button class='slim ghost' type='button' data-act='arriscar-ok' data-campo='"+c.id+"' data-valor='"+o.id+"'>"+esc(o.txt)+"</button>").join("")+"</div>").join("");}return"";}
function fechar(){stopTimer();const c=casoAtual(),jogador=idJogadorLocal();let txt="<p class='lede'>"+esc(c.fonteRevelacao||(c.titulo+" · "+c.fonte))+"</p><div class='reveal'>";CAMPOS.forEach(function(campo){const global=state.resolvidosGlobais[campo.id],pessoal=(state.errosPorJogador[jogador]||{})[campo.id],certa=campo.opcoes.find(o=>o.id===campo.resposta).txt;txt+="<p><b>"+esc(campo.rotulo)+"</b> "+(global?"Fechado corretamente para a mesa.":pessoal?"Você ficou com uma leitura incorreta. A resposta sustentada é: "+esc(certa)+".":"Ficou aberto. Os fatos sustentam: "+esc(certa)+".")+"</p>";});(c.revelacao||[]).forEach(linha=>{txt+="<p>"+esc(linha)+"</p>";});txt+="</div>";$("#score").innerHTML=txt;show("judge");}

function pintarLeque(){const box=$("#leque");if(!box)return;const n=Math.min(7,state.monte.length),mid=(n-1)/2;box.innerHTML=Array.from({length:n},(_,i)=>{const rot=((i-mid)*8).toFixed(1);return"<button type='button' class='carta-costa' data-monte-index='"+i+"' aria-label='Comprar carta "+(i+1)+"' style='--rot:"+rot+"deg;transform:rotate("+rot+"deg)'></button>";}).join("");box.querySelectorAll("[data-monte-index]").forEach(carta=>{carta.disabled=!suaVez()||state.verbo!=="comprar";carta.addEventListener("click",()=>comprar(Number(carta.dataset.monteIndex)));});}
function configurarHud(){const cell=$(".cell-saldo"),botoes=document.querySelectorAll("#verbos button"),tempoLabel=$(".tempo-inline small"),monteTitulo=$("#monte-titulo");if(cell)cell.classList.toggle("modo-quiz",modoQuiz());const label=cell&&cell.querySelector("small");if(label)label.textContent=modoQuiz()?"Campos":"Saldo";if(tempoLabel)tempoLabel.textContent=modoQuiz()?"Ritmo:":"Tempo:";if(monteTitulo)monteTitulo.textContent=(modoQuiz()?"Poço":"Monte")+" · "+state.monte.length;const nomes=modoQuiz()?{arriscar:["Responder",""],capturar:["Ler","fragmento"],comprar:["Comprar",""],consignar:["Revelação","final"]}:{arriscar:["Arriscar",""],capturar:["Capturar",""],comprar:["Comprar",""],consignar:["Consignar","no balaio"]};botoes.forEach(btn=>{const n=nomes[btn.dataset.verbo];btn.innerHTML="<span>"+n[0]+"</span>"+(n[1]?"<small>"+n[1]+"</small>":"");});}
function render(){const atual=quem(),jogador=idJogadorLocal(),minhaMao=mao(jogador);configurarHud();paintTimer();$("#vez").textContent=atual===jogador?"Você":(NOMES[atual]||"Jogador");$("#jogador-da-vez").textContent="Vez: "+(atual===jogador?"Você":(NOMES[atual]||"Jogador"));const purse=$("#purse");if(purse)purse.innerHTML=modoQuiz()?"<div class='quiz-mark' aria-hidden='true'>4</div>":"<div class='stash'><div class='stash-art' aria-hidden='true'><i class='bag'></i><i class='coin on'></i></div></div>";$("#saldo-numero").textContent=modoQuiz()?Object.keys(state.resolvidosGlobais).length+"/4":saldo(jogador);$("#ordem").innerHTML=ORDEM.map(id=>"<li class='"+(id===atual?"agora":"")+"'><span>"+esc(id===jogador?"Você":(NOMES[id]||"Jogador"))+"</span>"+(id===atual?"<small>DA VEZ</small>":"")+"</li>").join("");$("#log").textContent=state.log;$("#pistas-box").classList.toggle("fechado",!state.pistasAbertas);$("#pistas-chev").textContent=state.pistasAbertas?"FECHAR ▾":"ABRIR ▸";$("#hand").innerHTML=minhaMao.length?minhaMao.map(function(id){const p=peca(id),art=p.figura&&FIGURAS[p.figura]?"<img class='tile-art' alt='' src='"+FIGURAS[p.figura]+"'>":"";return"<div class='tile tipo-"+esc(p.tipo||"pista")+"'>"+art+"<small>"+esc(p.marca)+"</small><p>"+esc(p.texto)+"</p></div>";}).join(""):"<p class='log'>Nenhuma pista particular.</p>";pintarLeque();$("#monte-box").classList.toggle("compra-ativa",suaVez()&&state.verbo==="comprar");$("#monte-ajuda").textContent=!state.monte.length?"Poço vazio":(state.verbo==="comprar"&&suaVez()?"Toque em uma carta":"Escolha Comprar para retirar uma carta");document.querySelectorAll("#verbos button").forEach(btn=>{btn.classList.toggle("ligado",state.verbo===btn.dataset.verbo);btn.disabled=!suaVez();});const painel=$("#painel"),html=htmlPainel();painel.hidden=!html;painel.innerHTML=html;painel.querySelectorAll("[data-act='capturar-ok']").forEach(b=>b.addEventListener("click",()=>capturar(b.dataset.quem,b.dataset.id)));painel.querySelectorAll("[data-act='ler-ok']").forEach(b=>b.addEventListener("click",()=>lerPista(b.dataset.id)));painel.querySelectorAll("[data-act='consignar-ok']").forEach(b=>b.addEventListener("click",()=>consignar(b.dataset.id)));painel.querySelectorAll("[data-act='arriscar-ok']").forEach(b=>b.addEventListener("click",()=>arriscar(b.dataset.campo,b.dataset.valor)));}

function atualizarRegra(){const c=casoAtual();if(!c)return;const kicker=$("#rule-kicker"),title=$("#rule-title"),verbs=$("#rule-verbs"),lede=$("#rule-lede");if(!kicker)return;if(modoQuiz()){kicker.textContent="Mosaico-quiz · quando + o quê";title.textContent=c.lede;verbs.innerHTML="<li><b>Comprar</b> Retire um fragmento mudo do poço.</li><li><b>Ler</b> Leia em voz alta um fragmento que já possui.</li><li><b>Responder</b> Escolha uma opção em um dos quatro campos.</li><li><b>Fechamento</b> Acerto fecha para todos; erro fecha só para quem respondeu.</li>";lede.textContent="Mesa de 3 a 6. Dois fragmentos por participante. Sem moeda, captura, cronômetro, texto livre ou ranking.";}else{kicker.textContent="Demonstração · carta da ovelha";title.textContent="Uma demonstração da compra e da animação da carta especial.";verbs.innerHTML="<li><b>Arriscar</b> Acerto fecha para todos; erro fecha só para você.</li><li><b>Capturar · 2</b> Transfere uma pista capturável.</li><li><b>Comprar · 4</b> Toque numa carta do leque.</li><li><b>Consignar</b> Envia uma pista ao balaio.</li>";lede.textContent="A primeira compra é a ovelha: não cobra, rende 6 denários, permanece 5,5 segundos e sai do jogo.";}}
function pintarCasos(){const box=$("#casos");if(!box)return;box.innerHTML=["ovelha","emaus"].filter(id=>CASOS[id]).map(id=>{const c=CASOS[id];return"<button class='caso-btn' type='button' data-caso='"+id+"'><small>"+(id==="ovelha"?"Demonstração":"Mosaico-quiz · 3–6 jogadores")+"</small>"+esc(c.titulo)+"</button>";}).join("");box.querySelectorAll("[data-caso]").forEach(btn=>btn.addEventListener("click",function(){carregarCaso(btn.dataset.caso);show("rule");}));}

carregarCaso(casoId);
document.addEventListener("DOMContentLoaded",function(){pintarCasos();$("#go-rule").addEventListener("click",function(){atualizarRegra();show("rule");});$("#go-deal").addEventListener("click",startDeal);$("#again").addEventListener("click",function(){show("open");pintarCasos();});document.querySelectorAll("#verbos button").forEach(btn=>btn.addEventListener("click",()=>abrirVerbo(btn.dataset.verbo)));const toggle=$("#pistas-toggle");if(toggle)toggle.addEventListener("click",function(){state.pistasAbertas=!state.pistasAbertas;render();});});
