import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createContext, runInContext } from "node:vm";

const catalogSource = readFileSync(new URL("../cases-nt.js", import.meta.url), "utf8");
const runtimeSource = readFileSync(new URL("../bank-runtime.js", import.meta.url), "utf8");
const storage = new Map([["mc:nt:saco:v1", JSON.stringify({ ids: ["nt-001"], ultimo: "nt-052" })]]);
const context = createContext({ window: {}, globalThis: {}, localStorage: { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) }, Math, JSON });
context.globalThis = context; context.window = context;
runInContext(catalogSource, context); runInContext(runtimeSource, context);
const bank = context.MC_NT_BANK;
const eligible = bank.elegiveis();
assert.equal(eligible.length, bank.summary.playableCases);
assert.ok(eligible.length > 0, "o lote validado deve estar disponível");
const eligible6 = bank.elegiveis(6);
const eligible7 = bank.elegiveis(7);
const curtas = eligible6.filter(id => bank.byId[id].deck.maxPlayers === 6);
assert.equal(curtas.length, 8, "oito pautas curtas entram em mesas de até seis");
assert.ok(curtas.every(id => !eligible7.includes(id)), "pautas curtas ficam fora a partir de sete");
assert.ok(bank.elegiveis(12).every(id => bank.byId[id].deck.maxPlayers === 12));
const cycle = Array.from({ length: eligible.length }, () => bank.sortear().id);
assert.equal(new Set(cycle).size, eligible.length, "não repete antes de esgotar");
const next = bank.sortear().id;
assert.notEqual(next, cycle.at(-1), "não repete ao recompor");
assert.ok([...storage.keys()].some(key => key.includes(bank.namespace) && key.includes(bank.catalogVersion)));
const cycle6 = Array.from({ length: eligible6.length }, () => bank.sortear(6).id);
assert.ok(cycle6.every(id => eligible6.includes(id)));
const cycle7 = Array.from({ length: eligible7.length }, () => bank.sortear(7).id);
assert.ok(cycle7.every(id => eligible7.includes(id) && bank.byId[id].deck.maxPlayers >= 7));
assert.ok([...storage.keys()].some(key => key.endsWith(":j6")) && [...storage.keys()].some(key => key.endsWith(":j7")), "sacos persistidos são separados por capacidade da mesa");
assert.ok(storage.has("mc:nt:saco:v1"), "estado legado fica intocado e não é reutilizado");
console.log("ok saco versionado do novo banco");
